package constants

const DEFAULT_CONTEXT string = "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"

const ID string = "@id"
const TYPE string = "@type"
const VALUE string = "@value"
const DATE_TIME string = "https://uri.etsi.org/ngsi-ld/DateTime"
const PROPERTY string = "https://uri.etsi.org/ngsi-ld/Property"
const RELATIONSHIP string = "https://uri.etsi.org/ngsi-ld/Relationship"
const PROVIDED_BY string = "https://uri.etsi.org/ngsi-ld/default-context/providedBy"
const HAS_VALUE string = "https://uri.etsi.org/ngsi-ld/hasValue"
const HAS_OBJECT string = "https://uri.etsi.org/ngsi-ld/hasObject"
const CREATED_AT string = "https://uri.etsi.org/ngsi-ld/createdAt"
const MODIFIED_AT string = "https://uri.etsi.org/ngsi-ld/modifiedAt"
const OBSERVED_AT string = "https://uri.etsi.org/ngsi-ld/observedAt"
const DATASET_ID string = "https://uri.etsi.org/ngsi-ld/datasetId"
const INSTANCE_ID string = "https://uri.etsi.org/ngsi-ld/instanceId"
const UNIT_CODE string = "https://uri.etsi.org/ngsi-ld/unitCode"

const LOCATION string = "https://uri.etsi.org/ngsi-ld/location"
const GEO_PROPERTY string = "https://uri.etsi.org/ngsi-ld/GeoProperty"
const COORDINATES string = "https://uri.etsi.org/ngsi-ld/coordinates"
const POINT string = "https://uri.etsi.org/ngsi-ld/default-context/Point"
const LINE_STRING string = "https://uri.etsi.org/ngsi-ld/default-context/LineString"
const POLYGON string = "https://uri.etsi.org/ngsi-ld/default-context/Polygon"
const MULTI_POINT string = "https://uri.etsi.org/ngsi-ld/default-context/MultiPoint"
const MULTI_LINE_STRING string = "https://uri.etsi.org/ngsi-ld/default-context/MultiLineString"
const MULTI_POLYGON string = "https://uri.etsi.org/ngsi-ld/default-context/MultiPolygon"
const GEOMETRY_COLLECTION string = "https://uri.etsi.org/ngsi-ld/default-context/GeometryCollection"
const GEOMETRIES string = "https://uri.etsi.org/ngsi-ld/default-context/geometries"

const W3_ID string = "http://www.w3.org/ns/json-ld#id"
const W3_TYPE string = "http://www.w3.org/ns/json-ld#type"
const ID_PATTERN string = "https://uri.etsi.org/ngsi-ld/idPattern"
const NAME string = "https://uri.etsi.org/ngsi-ld/name"
const TIMESTAMP string = "https://uri.etsi.org/ngsi-ld/default-context/timestamp"
const START string = "https://uri.etsi.org/ngsi-ld/start"
const DESCRIPTION string = "https://uri.etsi.org/ngsi-ld/description"
const ENDPOINT string = "https://uri.etsi.org/ngsi-ld/endpoint"
const EXPIRES string = "https://uri.etsi.org/ngsi-ld/expires"
const INFORMATION string = "https://uri.etsi.org/ngsi-ld/information"
const PROPERTIES string = "https://uri.etsi.org/ngsi-ld/properties"
const ENTITIES string = "https://uri.etsi.org/ngsi-ld/entities"
const RELATIONSHIPS string = "https://uri.etsi.org/ngsi-ld/relationships"

const NOTIFICATION string = "https://uri.etsi.org/ngsi-ld/notification"
const WATCHED_ATTRIBUTES string = "https://uri.etsi.org/ngsi-ld/watchedAttributes"
const FORMAT string = "https://uri.etsi.org/ngsi-ld/format"
const URI string = "https://uri.etsi.org/ngsi-ld/uri"
const ACCEPT string = "https://uri.etsi.org/ngsi-ld/accept"
const ATTRIBUTES string = "https://uri.etsi.org/ngsi-ld/attributes"




