version: "2"
services:
    designer:
        image: fogflow/designer
        volumes:
            - ./designer-config.json:/app/config.json                
        ports:
            - 80:80
            - 1030:1030
        depends_on: 
            - discovery
            - broker
    discovery:
        image: fogflow/discovery
        volumes:
            - ./discovery-config.json:/config.json                        
        ports:
            - 443:443
        depends_on: 
            - postgis
    broker:
        image: fogflow/broker
        volumes:
            - ./broker-config.json:/config.json                        
        ports:
            - 8080:8080
        depends_on: 
            - discovery
    master:
        image: fogflow/master
        volumes:
            - ./master-config.json:/config.json                        
        links:
            - rabbitmq        
        ports:
            - 1060:1060 
        depends_on: 
            - rabbitmq
            - discovery
            - broker     
    worker1:
        image: fogflow/worker
        volumes:
            - ./worker1-config.json:/config.json                
            - /var/run/docker.sock:/var/run/docker.sock                    
    worker2:
        image: fogflow/worker
        volumes:
            - ./worker2-config.json:/config.json                
            - /var/run/docker.sock:/var/run/docker.sock                    
    worker3:
        image: fogflow/worker
        volumes:
            - ./worker3-config.json:/config.json                
            - /var/run/docker.sock:/var/run/docker.sock                    
    worker4:
        image: fogflow/worker
        volumes:
            - ./worker4-config.json:/config.json                
            - /var/run/docker.sock:/var/run/docker.sock                    
    postgis:
        image: mdillon/postgis
        ports:
            - 5432:5432        
    rabbitmq:
        image: tutum/rabbitmq
        ports:
            - 5672:5672
        environment:
            - RABBITMQ_PASS=mypass   
