FROM resin/raspberry-pi-python

RUN pip install flask

RUN pip install pyusb
RUN wget https://github.com/Eelviny/nxt-python/archive/v2.2.2.tar.gz
RUN tar -xvf v2.2.2.tar.gz
WORKDIR "nxt-python-2.2.2/"
RUN python setup.py install

RUN mkdir /lego
WORKDIR "/lego/"
ADD *.py /lego/
ADD *.json /lego/
ADD *.sh /lego/

CMD ["/bin/bash", "./start.sh"]
