FROM python:3.8-slim-buster

RUN mkdir /task
ADD main.py /task
ADD function.py /task
ADD config.json /task
ADD predictor.joblib /task
ADD requirements.txt  /task
WORKDIR /task

RUN pip3 install -r requirements.txt

CMD ["python3", "./main.py", "-o"]

