apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgeworker
spec:
  selector:
    matchLabels:
      run: edgeworker
  replicas: 1
  template:
    metadata:
      labels:
        run: edgeworker
    spec:
      containers:
      - name: edgeworker
        image: fogflow/worker:k8s
        imagePullPolicy: Always
        volumeMounts:
        - name: config-json       
          mountPath: /config.json
          subPath: config.json                
          readOnly: true                  
      volumes:
      - name: config-json 
        configMap:
          name: edge-configmap     
      serviceAccountName: default  
          


