#!/bin/bash
#build the linux version (amd64) of worker

if (( $# != 1 )); then
	echo "Illegal number of parameters"
	echo "usage: ./build [multistage|development]"
	exit 1
fi

command="$1"
case "${command}" in
	"multistage")
		     time docker build -f ./Dockerfile_multistage -t "test/worker:k8s" ../
		     ;;
	"development")
		      go get
		      CGO_ENABLED=0  GOOS=linux GOARCH=amd64 go build  -a -installsuffix cgo -o worker
		      time docker build -f ./Dockerfile_development -t "fogflow/worker:k8s" .
		      ;;
	*)
                      echo "Command not Found."
		      echo "usage: ./build [multistage|development]"
		      exit 127;
		      ;;	     
esac


#build the arm version of worker
#CGO_ENABLED=0  GOOS=linux GOARCH=arm go build  -a -installsuffix cgo    -o worker_arm
#docker build -f Dockerfile4Arm -t "fogflow/worker:arm"  .

#build worker for ARMv8
#CGO_ENABLED=0  GOOS=linux GOARCH=arm64 go build  -a -installsuffix cgo    -o worker_arm64
#docker build -f Dockerfile4Armv8 -t "fogflow/worker:arm64"  .
