FROM python:2.7-alpine

RUN mkdir /task
ADD main.py /task
ADD function.py /task
ADD config.json /task
ADD requirements.txt  /task
WORKDIR /task

RUN pip install -r requirements.txt

CMD ["python", "./main.py", "-o"]

