apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
spec:
  selector:
    matchLabels:
      run: master
  replicas: 1
  template:
    metadata:
      labels:
        run: master
    spec:
      containers:
      - name: master
        image: fogflow/master:k8s
        imagePullPolicy: Always
        ports:
        - containerPort: 1060    
        - containerPort: 8010                    
        volumeMounts:
        - name: config-json       
          mountPath: /config.json
          subPath: config.json            
          readOnly: true
      volumes:
      - name: config-json 
        configMap:
          name: fogflow-configmap   
      serviceAccountName: default  
           
---          
          
apiVersion: v1
kind: Service
metadata:
  name: master
  labels:
    run: master
spec:
  type: ClusterIP
  ports:
  - name: "1060"
    port: 1060
    targetPort: 1060
  - name: "8010"
    port: 8010
    targetPort: 8010
  selector:
    run: master
