#!/bin/bash

if (( $# != 1 )); then
	echo "Illegal number of parameters"
	echo "usage: ./build [multistage|development]"
	exit 1
fi

command="$1"
case "${command}" in
	"multistage")
		     time docker build -f ./Dockerfile_multistage -t "fogflow/designer"  ../
		     ;;
	"development")
		      npm install
		      time docker build -f ./Dockerfile_development -t "fogflow/designer" .
		      ;;
	*)
		      echo "Command not Found."
		      echo "usage: ./build [multistage|development]"
		      exit 127;
		      ;;
esac

#it is not possible to build the designer docker image for arm after adding dgraph
#docker build -f dockerfile4arm -t "fogflow/designer:arm"  .


