FROM node:11-alpine as builder
WORKDIR /go/src
ADD /designer designer/
WORKDIR /go/src/designer
RUN npm install

FROM node:11-alpine
COPY --from=builder /go/src/designer /app
WORKDIR /app/
ENTRYPOINT [ "node", "main.js" ]
